pub const STREAMERS: [&str; 78] = [
    "danielhe4rt",
    "xqc",
    "summit1g",
    "ninja",
    "shroud",
    "pokimane",
    "asmongold",
    "tfue",
    "myth",
    "drdisrespect",
    "sypherpk",
    "lirik",
    "timthetatman",
    "fextralife",
    "gaules",
    "loltyler1",
    "nickmercs",
    "ibai",
    "trainwreckstv",
    "rubius",
    "m0e_tv",
    "moistcr1tikal",
    "sodapoppin",
    "mizkif",
    "itslikelucas",
    "kaceytron",
    "trick2g",
    "forsen",
    "jericho",
    "cloakzy",
    "moonmoon",
    "admiralbahroo",
    "nihachu",
    "hasanabi",
    "swagg",
    "scarra",
    "valkyrae",
    "kaypea",
    "fuslie",
    "rakin",
    "s1mple",
    "itshafu",
    "reckful",
    "dakotaz",
    "esfandtv",
    "hiko",
    "nymn",
    "sweet_anita",
    "voyboy",
    "aptx",
    "neko",
    "grossie_gore",
    "jakenbake",
    "drluppog",
    "hanniballectah",
    "fuslie",
    "chocotaco",
    "doublelift",
    "nickeh30",
    "goldglove",
    "boxbox",
    "elrubius",
    "sashagrey",
    "syndicate",
    "greekgodx",
    "maximilian_dood",
    "destiny",
    "koil",
    "pestily",
    "angelskimi",
    "reckful",
    "ironmouse",
    "susu_jpg",
    "kinggothalion",
    "paymoneywubby",
    "stpeach",
    "mang0",
    "thedooo"
];

pub const USERS: [&str; 18] = [
    "danielhe4rt",
    "nadachi",
    "xqc",
    "summit1g",
    "ninja",
    "shroud",
    "pokimane",
    "asmongold",
    "tfue",
    "myth",
    "clintonrocha",
    "namelessblossom",
    "iza404",
    "usb777_",
    "thiagobento9",
    "lucasgabriel",
    "riko_dts",
    "kaduwaengertner"
];

pub const MESSAGES: [&str; 50] = [
    "hello",
    "hi",
    "hey",
    "how are you?",
    "good morning",
    "good afternoon",
    "good evening",
    "good night",
    "goodbye",
    "bye",
    "pogchamp",
    "kappa",
    "gg",
    "well played",
    "let's go!",
    "no way!",
    "wow, amazing!",
    "hype!",
    "let's get it!",
    "nice shot!",
    "omg!",
    "lol",
    "lmao",
    "brb",
    "back now",
    "let's do this!",
    "rip",
    "f",
    "clap",
    "hahaha",
    "that's crazy",
    "what a game!",
    "don't give up!",
    "i can't believe it!",
    "you're the best",
    "let's win this",
    "awesome play!",
    "who else is watching?",
    "any tips?",
    "this is intense!",
    "what just happened?",
    "love this game",
    "raid incoming!",
    "sub hype!",
    "anyone else here?",
    "first time watching",
    "chat is wild",
    "can we get some hype?",
    "love this stream!",
    "new follower here",
];
